#!/usr/bin/env python3
"""
AnimaLife — 2026-06-10 — Branded placeholder covers (2048x1152, 16:9).
Used when Gemini Image API free tier is exhausted (limit=0).
Creates visually branded covers using Pillow — warm gradient backgrounds
with AnimaLife color palette. Will be replaced by AI-generated versions
via regen_covers.sh when API quota is available.
"""

import os
import sys
import json
import math
from PIL import Image, ImageDraw

BASE = "/home/max/MAVII_AGENTS/projects/animalife/repos/animalife-rss"
W, H = 2048, 1152

# AnimaLife brand palette
PALETTES = {
    "cat_warm": [
        (200, 101, 74),   # terracotta
        (217, 168, 108),  # ochre
        (245, 239, 230),  # cream
        (74, 157, 209),   # accent blue
    ],
    "cat_cool": [
        (45, 74, 62),     # dark green
        (74, 157, 209),   # blue
        (245, 239, 230),  # cream
        (200, 101, 74),   # terracotta
    ],
    "dog_warm": [
        (217, 168, 108),  # ochre
        (200, 101, 74),   # terracotta
        (245, 239, 230),  # cream
        (45, 74, 62),     # dark green
    ],
    "dog_natural": [
        (45, 74, 62),     # dark green
        (217, 168, 108),  # ochre
        (245, 239, 230),  # cream
        (200, 101, 74),   # terracotta
    ],
}

COVERS = [
    # (slug, palette_key, gradient_angle_deg)
    ("cat-head-pillow-sleeping",       "cat_warm",    135),
    ("cat-whisker-fatigue-bowl",       "cat_cool",    160),
    ("cat-stares-at-wall-night",       "cat_cool",    180),
    ("cat-summer-hydration-tricks",    "cat_warm",    120),
    ("cat-greeting-tail-up",           "cat_warm",    150),
    ("dog-eats-grass-walk",            "dog_natural", 130),
    ("dog-circles-before-lying",       "dog_warm",    145),
    ("dog-leg-twitching-sleep",        "dog_warm",    160),
    ("puppy-bite-inhibition-train",    "dog_warm",    120),
    ("dog-crate-training-week",        "dog_natural", 140),
]


def lerp_color(c1, c2, t):
    return tuple(int(c1[i] + (c2[i] - c1[i]) * t) for i in range(3))


def make_gradient(w, h, color1, color2, color3, angle_deg=135):
    """3-stop gradient with slight radial vignette."""
    img = Image.new("RGB", (w, h))
    pixels = img.load()

    rad = math.radians(angle_deg)
    dx, dy = math.cos(rad), math.sin(rad)

    for y in range(h):
        for x in range(w):
            # Project point onto gradient direction
            t = ((x / w) * dx + (y / h) * dy + 1) / 2
            t = max(0.0, min(1.0, t))

            if t < 0.5:
                c = lerp_color(color1, color2, t * 2)
            else:
                c = lerp_color(color2, color3, (t - 0.5) * 2)

            # Subtle radial vignette
            cx, cy = (x - w / 2) / (w / 2), (y - h / 2) / (h / 2)
            dist = math.sqrt(cx * cx + cy * cy) / 1.4142
            vignette = max(0.0, 1.0 - dist * 0.3)
            c = tuple(int(v * vignette + 20 * (1 - vignette)) for v in c)

            pixels[x, y] = c

    return img


def add_brand_mark(img, palette):
    """Add a subtle AnimaLife brand stripe at bottom — no text, just color bar."""
    draw = ImageDraw.Draw(img)
    bar_h = 8
    # Thin accent bar at bottom
    accent = palette[3]
    draw.rectangle([(0, H - bar_h), (W, H)], fill=accent)
    # Softer line above
    draw.rectangle([(0, H - bar_h - 2), (W, H - bar_h)], fill=tuple(min(255, v + 40) for v in accent))
    return img


def generate_placeholder(slug, palette_key, angle):
    pal = PALETTES[palette_key]
    # Use first 3 palette colors for gradient stops
    img = make_gradient(W, H, pal[0], pal[1], pal[2], angle)
    img = add_brand_mark(img, pal)

    out_dir = os.path.join(BASE, "articles", slug, "images")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "cover.jpg")

    img.save(out_path, "JPEG", quality=85, optimize=True)
    size_kb = os.path.getsize(out_path) // 1024

    # Leave .placeholder marker so regen_covers.sh will replace with real AI cover
    placeholder_path = os.path.join(out_dir, ".placeholder")
    with open(placeholder_path, "w") as f:
        f.write(f"slug={slug}\npalette={palette_key}\ncreated=2026-06-10\n")

    return out_path, size_kb


if __name__ == "__main__":
    print("=== AnimaLife Placeholder Covers 2026-06-10 ===")
    print(f"Note: Gemini Image API free_tier limit=0 — creating branded placeholders")
    print(f"      Real AI covers will be generated by regen_covers.sh when quota allows\n")

    results = []
    for slug, palette_key, angle in COVERS:
        try:
            out_path, size_kb = generate_placeholder(slug, palette_key, angle)
            rel = f"articles/{slug}/images/cover.jpg"
            print(f"  OK  {rel}  ({size_kb}KB, palette={palette_key})")
            results.append((slug, True, f"placeholder {size_kb}KB"))
        except Exception as e:
            print(f"  FAIL  {slug}: {e}")
            results.append((slug, False, str(e)))

    ok_count = sum(1 for _, ok, _ in results if ok)
    print(f"\n=== {ok_count}/{len(COVERS)} placeholder covers created ===")
    print("Cron regen_covers.sh will upgrade to AI covers at 06:30, 09:30, 12:40 MSK")
